name: flutter_recepten_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_database: ^10.2.1
  flutter:
    sdk: flutter
  email_validator: ^2.0.1
  firebase_storage: ^11.2.3
  image_picker: ^0.8.9
  uuid: ^3.0.7
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
